### ISSUE TITLE
`about:support` button is incorrect color

### ISSUE THREAD

**Issue by TheBrokenRail** [black7375/Firefox-UI-Fix#1014]
### Describe the bug

The "Refresh Firefox" button in `about:support` is pink-ish instead of orange. And since I'm using Yaru, it should be orange.

### Expected behavior

It's orange like the other buttons.

### Screenshots

The Buggy Button:

![image](https://github.com/user-attachments/assets/57943306-450f-499e-8ebb-e3b331728167)

A Correct Button (Same Version):

![image](https://github.com/user-attachments/assets/d15e9b13-644d-419a-b863-6ed4e2b52ed9)

![image](https://github.com/user-attachments/assets/b42fba5e-2ba3-45ba-a2e1-d9b82aa21034)

### OS

Linux

### Firefox Version

v132.0

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

`Yaru-dark`

### `user.js` setup

- `userChrome.theme.system_default`
- `userContent.page.proton_color.system_accent`
- `widget.non-native-theme.use-theme-accent`

**Comment by Aleksandra0056** [comment]
No, that button uses the right colour. It was coloured red (a danger button colour) to prevent people from accidentally clicking on it. It's pink on Linux because of different colour schemes when compared to Windows.

The orange colour you depicted in screenshots is used for interaction buttons like "Save Changes" or "Accept the risk and continue" and not for danger buttons. Orange button colour on Ubuntu or other Linux distributions is equivalent to the blue button colour on Windows.

See more info about the change of the "Refresh Firefox..." button colour here: https://github.com/black7375/Firefox-UI-Fix/issues/941

**Comment by Aleksandra0056** [comment]
But on the other hand, you are right that it actually uses inconsistent colour. On Windows it's the colour `#E22850`, but on Linux, it's `#FF848B`, so re-colouring it to `#E22850` on Linux would be a good idea for consistency.

**Comment by black7375** [comment]
Yes, this may be an intentional color.

This is the `Primary button color`.

![image](https://github.com/user-attachments/assets/d15e9b13-644d-419a-b863-6ed4e2b52ed9)

And this is the button color that represents the `warining`.

![image](https://github.com/user-attachments/assets/57943306-450f-499e-8ebb-e3b331728167)

You are using the system colors, but different systems may use different colors.

Thank you for your kind report!!
