### ISSUE TITLE
Photon icons for photon-style?

### ISSUE THREAD

**Issue by dokax** [black7375/Firefox-UI-Fix#137]
Replace some new design icons with [photon icons](https://github.com/FirefoxUX/photon-icons)

**Comment by black7375** [comment]
No plans yet.
Many icons are gone, but there are a lot of icons I use internally.
Replacing all of them is time consuming and I don't think there is much to gain.

However, it seems like a good idea and I've added it to the wiki because it seems like someone might be looking for it.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#photon-icons

There is a possibility if we create a contrast mode after introducing JS. (requires bold icons)
