### ISSUE TITLE
First pinned tab shifts down by 1px when selected

### ISSUE THREAD

**Issue by osovitskiy** [black7375/Firefox-UI-Fix#177]
**Describe the bug**
When selecting first pinned tab its border and icon gets shifted down by 1px

**Expected behavior**
Icon should stay in place, blue border should touch top of the window

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/4147169/129787442-64800119-fa9c-44f7-a16f-3ba210dcd23c.png) ![Untitled1](https://user-images.githubusercontent.com/4147169/129787452-27043c26-ed2e-4265-b94d-3418cc84866c.png) ![Untitled2](https://user-images.githubusercontent.com/4147169/129787467-b17ff31c-2904-40f5-b245-c6c311edf589.png)

**Environment (please complete the following information):**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [x] Windows 8.1
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Comment by black7375** [comment]
**With titlebar**
![image](https://user-images.githubusercontent.com/25581533/129901478-95e4672c-910c-4491-8960-ea11e49516b5.png)
![image](https://user-images.githubusercontent.com/25581533/129901418-d65cdb9a-157b-4ebc-bbbf-bcde603bd873.png)

**None titlebar**
![image](https://user-images.githubusercontent.com/25581533/129901657-9dde0d9e-ba10-4691-8822-9dbbb3522b59.png)
![image](https://user-images.githubusercontent.com/25581533/129901713-c67c160d-1259-491b-8dc9-a0d0c0a3ba47.png)

**Maximize**
![image](https://user-images.githubusercontent.com/25581533/129901905-84272fb5-b5c3-4789-a69e-751e7dd410e5.png)
![image](https://user-images.githubusercontent.com/25581533/129901972-9484f1d9-a814-427e-98cb-e65225616c46.png)

It may have already been fixed in the latest version.

**Comment by osovitskiy** [comment]
I can confirm that the issue reproduces on my side on latest 'photon-style' snapshot.
Also on your screeshots there's an additional 1px border to the left of the selected tab which doesn't appear on my side. Maybe it something to do with the system screen scaling settings? I'm using default 100% scaling.

**Comment by black7375** [comment]
I found and fixed the bottom of the  pinned  tab is detached in my VM.
If you're lucky with this patch, it might be fixed.

**Comment by osovitskiy** [comment]
The patch works for me!
Thanks for addressing this, I'm closing the task.
