### ISSUE TITLE
Reload tab button's icon is missing

### ISSUE THREAD

**Issue by Tomava** [black7375/Firefox-UI-Fix#194]
**Describe the bug**
Reload tab button's icon is missing.

**Expected behavior**
Reload tab should have an icon.

**Screenshots**
![Reload_tab_missing](https://user-images.githubusercontent.com/66073405/130815015-eff17c19-dfd8-4c91-914d-da5ea64bc6fc.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Additional context**
This bug was introduced in 3.2.0

**Comment by black7375** [comment]
Reload icon was intentionally removed.
https://github.com/black7375/Firefox-UI-Fix/commit/fc4d67dfefb031ede16e09b32474638fba37cbc7

Accessible reload button are on the toolbar, and this was done to make it easier to see `Mute tab`, `Pin tab`, and `Duplicate tab`, ..etc, which are only accessible from the tab context menu.

I left the code as a comment because I thought there might still be users who would like it.
