### ISSUE TITLE
Unify icon design langauge

### ISSUE THREAD

**Issue by ildiem** [black7375/Firefox-UI-Fix#213]
**Is your feature request related to a problem?**
The icons in the context menu, as well as the main menu, seem to be taken from different sources, making them look mismatched.

**The solution I'd like**
Any new icons should follow Proton's design language (or whatever standard you'd prefer).

**Additional context**
For example, different icons have different stroke thicknesses, as a result of being from different icon sets.
![Screen Shot 2021-09-07 at 6 04 57 PM](https://user-images.githubusercontent.com/81544216/132419351-9bcf34b4-f8aa-48e0-bc72-13891a8ddc72.png)

**Comment by black7375** [comment]
I'm not a designer and I'm not good at using tools, so it may take a long time to fix them.

---

## Info
If anyone wants to work on icons.

## Known issues with current icons.
- As reported, the thickness is not uniform.
- Some icons are not `16x16` in size.
- Some icons with too much inner padding.

## When working
It can be seen as transparent because of the `fill="context-fill" fill-opacity="context-fill-opacity"` property.
Fill in the color first and then proceed with the work.

https://github.com/black7375/Firefox-UI-Fix/blob/64c7eeebfbf025c02cff787f3dafade54707dd9a/icons/arrow-sort-down-lines.svg#L1

## Icon post-processing
There is something to work on after modifying the icon.
- **Optimization**: Graphic programs generate code without caring about optimization. It should be optimized using [SVGO](https://github.com/svg/svgo). It's also available [online](https://jakearchibald.github.io/svgomg/).
- **Property**: `width`, `height`, `viewBox`, `fill="context-fill`, `fill-opacity="context-fill-opacity"` properties should be included.

**Comment by MarNicGit** [comment]
Do these icons exist in older versions of Firefox? Maybe it's possible to retrieve them from their source code archives?

**Comment by black7375** [comment]
## Icon classification

### 1. Browser built-in icons

**Issue**
- thickness is not uniform.

**Icons**
![image](https://user-images.githubusercontent.com/25581533/132778503-586d71cc-ddcc-45e8-be63-3b9a033199ae.png)
- Save Page
- Open File
- Edit Controls
- Repair text encoding
- Email Link
- Screenshot
- Forget
- Developer tools icons

### 2.  Photon Icons

**Issue**
- thickness is not uniform.

**Source**
- https://github.com/FirefoxUX/photon-icons
- https://design.firefox.com/icons/viewer/

### 3. Fluent Icons

**Issue**
- Some icons not `16x16` in size.
- Some icons with too much inner padding.

**Source**
I am using it because it is most similar to Proton's icon.
- https://github.com/microsoft/fluentui-system-icons

---

I'll try to document it as soon as I have time.

**Comment by BPower0036** [comment]
In this repro https://github.com/BPower0036/FireFox_UserChrome you have most icons used in Firefox in Fluent design; this means that every icon will be the same as in Edge

**Comment by zapSNH** [comment]
I can work on this. I've already done a bunch of icons but there's still many more to go. The ones that I've done are not in any particular order and I've also redone some icons that were blurry.

See: https://www.figma.com/file/Iyym2tjRVlb7rxTR1Gmvr8/lepton?type=design&node-id=0-1&mode=design

(tip: set the zoom to 100% to see how it should look when used)

**Comment by black7375** [comment]
@zapSNH Wow. It's 100% set, so it's easy to compare with the blurry icon!!
It's an issue that's been open for a long time, so I think it'll be cool if it's applied.

---

Overall, the icons have been improved, but there are some things that I want to maintain the metaphor for easy recognition.

For example, a folder icon. https://github.com/black7375/Firefox-UI-Fix/issues/33#issuecomment-853624879
There was an opinion that the original folder icon is close to a square, so it is difficult to recognize.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/ef6a50cd-ac28-4fba-b09b-a866483d8911)

And It also feels like animation when it's open.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/7a66a727-bcf0-467e-8cb3-8a04071c771e)

I will write some feedback within tomorrow and comment on it!!
I love your work. :+1:

**Comment by black7375** [comment]
## Feedback

Captured with Zoom 500%.
I would like to express my gratitude for your work before full-fledged feedback.
Your work feels good in the following side:
- Consistent shape and thickness
- Clean when it is Zoom 100% (Especially, text!!)
- Simplification of shape
- Looks more modern

Please feel free to let me know if you have any ideas that differ from mine.

### 1. Folder
Thank you for reflecting my opinion.

1. The size of the folder on the right should be constant.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/351cc2cf-9cd1-46ba-af87-4916242182f8)


### 2. Tab

The difference from the previous one is the tab shape and the filling.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/72c344f7-8cb0-4bb5-b7b7-cff3a5ee32f1)

1. I think it would be nice to see the icon different depending on the mode.
   (Need connect to toolbar like shape version too)

It looks like a new tab in Firefox, so it looks good.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/d078b0a8-e404-4fb6-84d5-189fbb58f6c0)

This project also supports other tab shape (conneted to toolbar).
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/f30459b4-fa40-47fb-8f1f-3d71d4907cc7)

Maybe there are the next icons.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/e2b78f9b-f866-4e13-98c8-3bb52be1c412)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/88f381c9-c29e-4fde-93b7-40e4e4baa386)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/f1219e58-3701-40c4-a2d9-675cbb7c2011)

2. `New tab` icon should be filled **only**. (Other tab images look as empty as they currently are.)

Consistency is partially sacrificed, but filled icons serve as a emphasize.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/77fa6164-aef4-4889-a8bc-f4c63b5abe48)

Compared to the panel of the edge, it is relatively easy to distinguish.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/04cc8842-a44a-4ba1-a137-fc22d553f18d)

It is natural to emphasize the creation of new tab in the menu that appears when you right-click on a new tab button.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/f0d21038-0475-4b75-8fa8-2c711da39fb4)


### 3. Bookmark toolbar

- Since it is a toolbar, I think the rectangle will be more suitable than the square.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/19ee3565-df95-410e-b8e8-d650ad6dc0b9)


### 4. Clockwise

- It means the past time state, so I hope the direction of the needle is different.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/c86abd8e-b6f6-46d8-b466-5a66427a3bbb)

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/46309ea9-daf5-42c1-8456-3df1cde9b0cd)

### 5. Tablet

- How about small vertical bar add to right side?

It distinguishes the shape of the tab and is consistent with the shape of the phone.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/01f41e29-2049-4c28-b8e5-e10fed445401)

### 6. Clipboard

1. It would be better to have a size of the third bar twice.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/7fd68336-cffc-4c44-b642-2d78c4e7cd8f)

If zoom is 100%, the third bar looks small.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/3da5a797-4c2f-4f9a-9d6a-5894743e1b4f)

In other icons, it feels like it looks appropriate.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/6997ff8c-9f98-41d6-bdcc-aa937ca67178)

2. Broken arrow

It appears to be disconnected.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/ef83585b-bf3d-4a99-bb60-ebafdc5ae477)

### 7. Dictionary

1. The title bar is out of balance

I think it will look better if there is a adjustment in the width and the inner space size.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/608803b6-0b4b-4c1b-9aa1-74bf00b5edc7)

2. The bottom right of the first dictionary

I think I'll look better if it round or empty.

### 8. Password Field

- I think the matching is wrong

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/736b05b1-9ad3-4d34-89f5-e31c1df83fa9)

### 9. Duplicate window & Select all tab

As you may have felt while making it, the meaning of these three icons is a bit confusing. (from the beginning)

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/0dfedc93-9d51-48a9-ba53-8eaffe27b517)

- Duplicate tab
- Duplicate Window
- Select all tabs

The first one is the tab itself, so you don't have to touch it.

- The second is Window`, so there should be a tab strip.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/a3464afb-013b-4ba7-86e7-71fd3d306c8e)
- The third is that we select all the tabs of Windows, so I hope it will be distinguished like the previous shape.

### 10. Tag

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/cb1e3b71-dee2-4210-b7d8-d0bdf9db98f6)

- An additional tag icon is required to indicate when there is content
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/0fd4a910-8dfb-4716-a452-a04bec9527e8)

### 11. Gift box

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/0b319ab3-2bf9-4433-98db-e4dae4a2f077)

- The string of the gift box should be connected
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/e18734c7-fb96-4df1-add8-49d0793b7a79)
(https://www.indiamart.com/proddetail/handmade-explosion-gift-box-22417871112.html)

---

**Comment by zapSNH** [comment]
Thanks for your feedback. I have applied the feedback to most icons.
However, I have some questions.

> ### 3. Bookmark toolbar
> 
>- Since it is a toolbar, I think the rectangle will be more suitable than the square.
> 
> 
> ![image](https://user-images.githubusercontent.com/25581533/277104989-19ee3565-df95-410e-b8e8-d650ad6dc0b9.png)
 
I have tried to make it a rectangle but at 100% zoom (i.e. 100% scaling) it'll either:

- look weird (less than 1px between star and border) or
    ![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/bc0f99d1-a6f4-4374-a5de-dfcddcee50cc)

- have `bookmarksToolbar-open` be almost indistinguishable from the regular icon
    ![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/a085f399-facf-470e-9ab7-248a6dc49737)

>2.  Broken arrow
>
>It appears to be disconnected.
>![image](https://user-images.githubusercontent.com/25581533/277104778-ef83585b-bf3d-4a99-bb60-ebafdc5ae477.png)

This is because there are two icons in each svg. This is how it should look like if they were separate.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/01aa04c1-31b1-49b3-ba80-fc1e4b368704)

If you only use one then I can delete the other one in order to free a tiny bit of storage space.

> ![image](https://user-images.githubusercontent.com/25581533/277108113-0dfedc93-9d51-48a9-ba53-8eaffe27b517.png)
> - Duplicate tab
> - Duplicate Window
> - Select all tabs
> 
> The third is that we select all the tabs of Windows, so I hope it will be distinguished like the previous shape.

Would this look okay for "Select all tabs"?
![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/7556fcc8-6348-4e6a-9cc7-a8c7b1ed48b8)

**Comment by black7375** [comment]
> (less than 1px between star and border)

I think it's okay to be almost full (In fact, there are few margins of the bookmark toolbar, and it looks better than it is not distinguished)

> This is because there are two icons in each svg. This is how it should look like if they were separate.

Thank you, it's separated so I think I can take it and use it if I need it.

> Would this look okay for "Select all tabs"?

It looks good. It's much better than I imagined!! :heart_eyes: 

---

After solving the #799 bug tomorrow, I'm going to apply the icon right away.

**Comment by zapSNH** [comment]
Here's the repo with all the icons optimized:
https://github.com/zapSNH/lepton-icons/

**Comment by black7375** [comment]
I'm happy to be able to close an issue that's been open for two years.
Thanks @zapSNH !!
