### ISSUE TITLE
Improve code quality of the project

### ISSUE THREAD

**Issue by akisblack** [black7375/Firefox-UI-Fix#234]
**Is your feature request related to a problem?**
Yes, the code quality of this project is kinda bad and not documented.

**The solution I'd like**
Using SCSS and compiling it after would be ideal since it could be split up into multiple files, use nesting and other useful features SCSS provides.

**Alternatives I've considered**
None really. Unless someone goes out of their way to document all this single file mess I don't think this codebase will hold up for much longer.

**Additional context**
[SCSS site](https://sass-lang.com/)

**Comment by black7375** [comment]
I was also considering it.

1. Currently, I only keep it as a css file for people's customization. (SCSS requires compilation)
2. It reduces mistakes in the manual installation process and does not split files due to performance problems of `@import`.
3. JS will probably be introduced in the future, and if it can be controlled as an option in the settings window, we will use the SCSS method.

Thank you for your interest in the project.

**Comment by akisblack** [comment]
Yeah, your third point seems really exciting. Thanks for the response

**Comment by black7375** [comment]
It's a little late, but I started the migration.
https://github.com/black7375/Firefox-UI-Fix/tree/scss

**Comment by black7375** [comment]
Built with SASS from version `v5.0.0`.
