### ISSUE TITLE
too much space between last tab and button new tab

### ISSUE THREAD

**Issue by gabri25ele** [black7375/Firefox-UI-Fix#27]
![sshot-1](https://user-images.githubusercontent.com/33927879/120440650-0f04bc00-c384-11eb-907c-8e49451c297a.png)

the button new tab (Ctrl+t) it should be closer to the last tab.

😉

**Comment by black7375** [comment]
Adjustments are possible as follows:
![image](https://user-images.githubusercontent.com/25581533/120443626-5be19600-c376-11eb-8599-7e14a41ef2b8.png)
![image](https://user-images.githubusercontent.com/25581533/120444078-cf83a300-c376-11eb-879e-5b3aa0f46957.png)

However, size of the new tab icon is so big that it may look tight.

**Comment by gabri25ele** [comment]
> It's a better?

yes, it's better 😀

**Comment by black7375** [comment]
Applied.

**Comment by ojaha065** [comment]
Am I the only one who thinks that there's still way too much margin between the last tab and the plus icon? See the screenshots below.

![Screenshots](https://user-images.githubusercontent.com/37581768/121382345-2aa52f00-c94f-11eb-8465-845240873068.png)


I can see that in commit 8ea7358 the margin between the last tab and the icon was lowered to 4px from 8px. For the screenshot above I used margin of -4px... The problem is that now the hover effect of the icon is overlapping with the tab. Would it be possible to make the hover effect a little smaller?

This is pretty minor thing, I know. 😁  But I literally notice it every single time I open the browser.

**Comment by gabri25ele** [comment]
> 
> 
> Am I the only one who thinks that there's still way too much margin between the last tab and the plus icon? See the screenshots below.

I set up my userchrome like this and that's fine for me

  /* Latest Tab & New tab margin */
  #tabbrowser-arrowscrollbox:not([overflowing]) .tabbrowser-tab[last-visible-tab] {
    **margin-inline-end: 1px !important;**
  }

**Comment by black7375** [comment]
We need to adjust the icon padding, and we didn't do it because the shape of `+` could change when adjusting the padding.

I can try it later when you have enough time.
