### ISSUE TITLE
"Eyedropper" and "Extensions for Developers" have their icons switched

### ISSUE THREAD

**Issue by PencilAmazing** [black7375/Firefox-UI-Fix#36]
**Describe the bug**
In the More Tools submenu, "Extensions for Developers has an eyedropper icon, while the eyedropper has a terminal icon.

**Expected behavior**
The eye dropper has an eye dropper!

**Screenshots**
Menu -> More Tools

**Environment (please complete the following information):**
 - Firefox Version: 89.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
None.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/120568889-5d599f80-c404-11eb-9485-88fc80f5a3ec.png)

More tools are often obscure how to identify each.
So it's hard-coded in order.
https://github.com/black7375/Firefox-UI-Fix/blob/8ea735862467ebc52800649b76531b8b1e0ace35/userChrome.css#L799-L831

This seems to be because the amount of items varies depending on whether the debugging option is enabled.

**Comment by PencilAmazing** [comment]
![iconsMixedUp](https://user-images.githubusercontent.com/16854231/120600597-9f5d0280-c451-11eb-8ced-f4ff92c89e06.png)
Maybe something that counts the number of siblings an element has, and applies the icons differently then?

**Comment by black7375** [comment]
@PencilAmazing  `icons` directory position at `chrome` directory?
