### ISSUE TITLE
Firefox 104a - Drag + drop URL not working at top of tab bar

### ISSUE THREAD

**Issue by dcog989** [black7375/Firefox-UI-Fix#426]
Drag + drop works on most of the tab bar but not the top pixel or two - see:

![2022-06-30_222929](https://user-images.githubusercontent.com/89043002/176781563-3e7381b0-942d-4341-9662-436ab5e7bdb1.png)

**Comment by dcog989** [comment]
Added Firefox 104a to title.

**Comment by SBareS** [comment]
The issue seems to be the padding above the tabs. Simmilarly, clicking on top of a tab does not switch to the tab, because you are clicking the padding, not the tab. I worked around both of these issues by changing `user_pref("userChrome.padding.tabbar_height", true);` to `user_pref("userChrome.padding.tabbar_height",     false);` in user.js. That's looks a bit less nice of course, but at least it's usable.

**Comment by black7375** [comment]
IMO, It's reosolved #476
