### ISSUE TITLE
Inquiry: Theme colors to match current default?

### ISSUE THREAD

**Issue by yokoffing** [black7375/Firefox-UI-Fix#456]
I'm new to the repo, so forgive me if this is a n00b question. I don't think it's a bug.

I like Proton's (current UI) default light and dark theme. But after applying `Lepton's Proton style`, the theme changes to more of a grayish backdrop. See below:

![default](https://user-images.githubusercontent.com/11689349/186286378-12314a4f-8479-4627-a6a7-28da65ddbb1b.png)
Default Dark 

![uifix](https://user-images.githubusercontent.com/11689349/186286405-ddc4856d-cde3-46c3-a40b-18ff85ff699e.png)
Lepton Proton Dark

Is this intentional? How do I keep the current, default theme colors?

If it is a bug, I'll fill out the form and copy+paste what I use below.

**Comment by black7375** [comment]
Yes, It is an attempt to match the color of Windows 10 with intentional change. (Legacy Edge's Color Set)

Select one in two ways to use the original color theme.
- `userChrome.theme.system_default` to `false` (Edit `<FIREFOX_PROFILE>/user.js`)
- Go to `about:addons` -> `Themes` -> Enable `Dark` theme

**Comment by yokoffing** [comment]
> `userChrome.theme.system_default` to `false`

This worked. Thank you!
