### ISSUE TITLE
Consistent icons

### ISSUE THREAD

**Issue by Hidetoshi6721** [black7375/Firefox-UI-Fix#496]
**Is your feature request related to a problem?**
I really like Lepton's UI. Bringing back of the hamburger menu icons, or just the menu icons alone, is a great saving grace. However, unfortunately the icons are pretty inconsistent. One follows a "thin lines" kinda style, and the other has a bold, wider character.

**The solution I'd like**
I'd like all the icons to be uniform and adopting the Proton style. The thin strokes style.

**Screenshots or video**
![image](https://user-images.githubusercontent.com/85873175/198228913-3fac78e1-8b07-4163-920a-9b6f50206b74.png)

**Comment by patrik-krajcovic2** [comment]
The “Save page as…” icon is updated in PDF reader, just give me a moment, I will attach a screenshot.

**Comment by patrik-krajcovic2** [comment]
![Screenshot of PDF reader](https://user-images.githubusercontent.com/69351811/198233222-d0311c43-bee6-4434-81e1-c9075668cf3e.png)

**Comment by black7375** [comment]
First, I replaced the `file save` icon as suggested.
Let's deal with the rest in #213

---

IMO, I think the line icon and the filled icon can be mixed to increase the possibility of scanning.
However, it should be consistent with the form, and the thickness of the line icons must be fixed in the long run.
