### ISSUE TITLE
Inconsistent bookmark icons

### ISSUE THREAD

**Issue by patrik-krajcovic2** [black7375/Firefox-UI-Fix#497]
I found inconsistency between search bar bookmark icon and menu bookmark icon. One icon is filled, and one icon is empty, I will attach screenshot for better understanding.

The screenshot is in Slovak language, but I hope you don't mind.

![Incosistent bookmark icons](https://user-images.githubusercontent.com/69351811/198575888-e773336c-6ba1-4e92-a1d7-11d20dd220d8.png)

**Comment by black7375** [comment]
This is not a bug, but an intentional decision.

1. The icon filled in comparison is more visual balance.
![image](https://user-images.githubusercontent.com/25581533/198578095-663512e9-5415-44c8-87d2-9173f1947f1e.png)
![image](https://user-images.githubusercontent.com/25581533/198578194-af48959f-0305-40bb-aeff-2174f379d863.png)
2. The filled icon implies that it has already been bookmarked.
![image](https://user-images.githubusercontent.com/25581533/198578768-9bd394cd-ce18-48cb-bf97-7f1713c80826.png)
![image](https://user-images.githubusercontent.com/25581533/198578823-257569ca-36cc-48de-ade3-c801f5dbbb62.png)

---

Later, if both lines and filled icons are made for each icon, it will be available as an option, but there is no contribution at this time.
