### ISSUE TITLE
Large gray line separating the tab from the tab bar

### ISSUE THREAD

**Issue by tormater-yak** [black7375/Firefox-UI-Fix#499]
**Describe the bug**
Large gray line separating the tab from the tab bar

**Expected behavior**
Tabs should be connected to the tab bar

**Screenshots**
Ambiance: ![image](https://user-images.githubusercontent.com/115832947/198900221-fc21f502-c3f3-45e8-8c34-25a0afe9525c.png)
Light: ![image](https://user-images.githubusercontent.com/115832947/198900295-2d44ee9d-30ce-4d8f-af00-d05f7405f635.png)

**Environment:**

 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  	91.11.0esr
 - OS:
   - [X] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
    Ambiance - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**
Occurs on any theme I select, except Dark

**Comment by tormater-yak** [comment]
I'd also like to note that this only occurs while my GTK theme is set to Ambiance.

**Comment by black7375** [comment]
## Investigation Report

**Environment**
- OS: Ubuntu 22.04.1 LTS x86_64

Yaru
![image](https://user-images.githubusercontent.com/25581533/199249349-9a1be355-57c6-4efb-8d1b-26a25bf739bf.png)

Adwaita
![image](https://user-images.githubusercontent.com/25581533/199249490-9fce3b56-c90c-438e-a71b-9c4f7b6dcf07.png)

Ambiance [REPRODUCE]
![image](https://user-images.githubusercontent.com/25581533/199249059-13c13b41-3e1f-4f55-8515-7f5fe467f651.png)

Ambiance - Bundle light [REPRODUCE]
![image](https://user-images.githubusercontent.com/25581533/199251723-be4bc5dc-132e-4e2f-a087-cf2f4f44d687.png)

Ambiance - Bundle Alpenglow [REPRODUCE]
![image](https://user-images.githubusercontent.com/25581533/199250938-7fb96279-770c-4acc-b9e6-0f2ca04d4dad.png)

Ambiance - Bundle Dark
![image](https://user-images.githubusercontent.com/25581533/199251126-7dc7f386-4d69-4820-b5db-5607d62878a9.png)

It is a problem that only occurs in `Ambiance`'s bright themes.

---

### After patch

Now I see it as normal.
![image](https://user-images.githubusercontent.com/25581533/199255040-c422b62b-d99c-4198-95e4-813a469c21e7.png)

The size of `titlebar buttons` is not controlled, but it cannot be adjusted because of `appearance: auto`.
![image](https://user-images.githubusercontent.com/25581533/199255400-80ebb503-cd0e-44b1-84a1-0bddc7de8b5b.png)

**Comment by tormater-yak** [comment]
![image](https://user-images.githubusercontent.com/115832947/199287200-721dd298-8b0f-41e8-bc1d-16b7ccebebd7.png)
After updating, the gray line is gone.

**Comment by black7375** [comment]
Thanks for test :+1:
