### ISSUE TITLE
Windows10 Native menu layout

### ISSUE THREAD

**Issue by iansquenet** [black7375/Firefox-UI-Fix#541]
The tabs seems to be okay-ish, although inactive ones are not lit up. Also the context menu is completely unchanged (as noted on the last screenshot).

What I tried doing:
- Manual installation
- Powershell script installation

Operating System: Windows 10 Pro, version 22H2

![image](https://user-images.githubusercontent.com/36297463/208489659-1b8ad38f-4d6a-4250-9a59-f50fb7668c23.png)
![image](https://user-images.githubusercontent.com/36297463/208489277-c62072f8-a3d4-4d81-bc54-0335fc0d90ad.png)

**Comment by black7375** [comment]
> Also the menus are unchanged.

What do you mean?

**Comment by iansquenet** [comment]
> > Also the menus are unchanged.
> 
> What do you mean?

Referring to the last image :)

**Comment by black7375** [comment]
Little more cleary, what kind of changes do you expect?
The image above matches the context menu I want.

**Comment by iansquenet** [comment]
> Little more cleary, what kind of changes do you expect? The image above matches the context menu I want.

This is the look I wanted to go for, which didn't work. Sorry for being great at explaining.
![image](https://user-images.githubusercontent.com/36297463/208541469-dc0dc6cb-611a-4dc9-a0cb-b7faf6f9ea44.png)

**Comment by black7375** [comment]
Ok, It is possible by setting `browser.display.windows.non_native_menus` to `0`.

https://github.com/mozilla/gecko-dev/blob/516dbdf21e2e0aafe702400d632ee17f0375d361/modules/libpref/init/StaticPrefList.yaml#L1139-L1147

But there is a bug because it was made without considering native menu.

---

Original Native menu
![image](https://user-images.githubusercontent.com/25581533/208545742-1bf261d2-d4b7-4e30-8c18-34e7a0cea6b0.png)

Bugged
![image](https://user-images.githubusercontent.com/25581533/208545730-046ec6f0-e905-476b-8a92-3279db2ea612.png)

---

But making the next layout must create a completely new feature.

![image](https://user-images.githubusercontent.com/36297463/208541469-dc0dc6cb-611a-4dc9-a0cb-b7faf6f9ea44.png)

**Comment by black7375** [comment]
Now, will be works
![image](https://user-images.githubusercontent.com/25581533/208764903-64c2cc50-a5da-48e2-bac9-a601fb89b91e.png)
