### ISSUE TITLE
Pinned tab favicon showing

### ISSUE THREAD

**Issue by LordRishav** [black7375/Firefox-UI-Fix#58]
**Is your feature request related to a problem? Please describe.**

The close button for a pinned tab is shown instead of the favicon

**Describe the solution you'd like**

The close button should be replaced by the favicon for the website for aesthetic reasons. Just like in Photon:

https://i.imgur.com/vLcN3rW.png

The current pinned tab situation in Lepton:

https://i.imgur.com/e6JAFJ3.png

**Describe alternatives you've considered**
N/A

**Additional context**
This issue is a feature request, and the fix is merely for aesthetic reasons

**Comment by black7375** [comment]
Currently, I am focusing on bug fixes rather than major feature changes for release #31.
There have been several similar requests, and I understand.

It will definitely be reflected in the next release.
But it is not reflected now.

---

Temporary solution.
https://github.com/black7375/Firefox-UI-Fix/compare/hide-closebutton-at-pinned

Duplicate #10
