### ISSUE TITLE
Firefox Proton: Center Tab Label

### ISSUE THREAD

**Issue by Yaron10** [black7375/Firefox-UI-Fix#71]
Hello,

The following CSS code used to center the tab label prior to Proton.
```
.tab-label { -moz-box-flex: 1 !important; text-align: center !important; }
```
Any idea how to achieve that in Proton?

Thank you.

**Comment by sean1138** [comment]
```
.tab-label-container.proton{display: grid;  place-items: center;}
```
works fine for one tab with short text, did this used to make a mess of tabs as seen above my 'test' tab?
![image](https://user-images.githubusercontent.com/6720184/121227048-b1d4a300-c87a-11eb-9165-3d0a0a29c9de.png)

**Comment by Yaron10** [comment]
Thanks for replying. I appreciate it.

I've also played with`.tab-label-container.proton`. The same mess.

`.tab-label { -moz-box-flex: 1 !important; text-align: center !important; }` worked properly pre-Proton.
You can disable Proton (in FF 89/90) and test it.

**Comment by sean1138** [comment]
doen't mess up multiple tabs open
```.tab-label-container.proton{display: grid;  place-items: center;}
.tab-text.tab-label{overflow:hidden;}```
![image](https://user-images.githubusercontent.com/6720184/121228853-c9ad2680-c87c-11eb-9beb-26d29d65c874.png)

**Comment by Yaron10** [comment]
I've just quickly tested it. It looks great. 👍 
Thank you so much.

It requires some fine-tuning.
My system is RTL (Right To Left), Hebrew.
Note the difference in the following links:

https://github.com/notepad-plus-plus/notepad-plus-plus

**Proton Disabled**
![תמונה](https://user-images.githubusercontent.com/10229320/121233942-d8570600-c89b-11eb-8480-c0ab7f2ef0c3.png)

**Proton Enabled**
![תמונה](https://user-images.githubusercontent.com/10229320/121234235-2a982700-c89c-11eb-98b7-5ecc811b167f.png)

https://github.com/black7375/Firefox-UI-Fix

**Proton Disabled**
![תמונה](https://user-images.githubusercontent.com/10229320/121234406-574c3e80-c89c-11eb-9c79-77a443b09306.png)

**Proton Enabled**
![תמונה](https://user-images.githubusercontent.com/10229320/121234496-6f23c280-c89c-11eb-9370-e7c5c15c2fc3.png)

**Comment by sean1138** [comment]
removing .proton from the .tab-label-container elector works for both proton and disabled.
```
.tab-label-container{display: grid;  place-items: center;}
.tab-text.tab-label{overflow:hidden;}
```

**Comment by Yaron10** [comment]
This is what I get with Proton enabled.

![תמונה](https://user-images.githubusercontent.com/10229320/121238160-7947c000-c8a0-11eb-9c4c-956a7f81a6db.png)

**Comment by Yaron10** [comment]
```
.tab-label-container.proton { display: grid !important;  justify-items: safe center !important; }
.tab-label { overflow: hidden !important; }
```

Seems to work properly with Proton enabled.
Could you please test it?

Thank you.

**Comment by sean1138** [comment]
interesting, i was not aware of the `safe` [keyword](https://www.w3.org/TR/css-align-3/#overflow-values).
something that's driving me nuts is the tab text will jump when i mouse over it and i have no idea why it doesn't happen on my middle tab as seen in the video.  It doesn't happen with proton disabled.
https://files.catbox.moe/qby8g0.mp4

using the safe option it looks like the text only gets centered if it's shorter than the width of the container.

i started using more specific selectors for the tabs on my end because if proton is enabled/disabled firefox has different elements displayed for the tab text.  it hasn't helped me figure anything out really but might be noteworthy that firefox does this - it doesn't just remove the .proton class from the vbox element like i initially assumed when proton is disabled.

```
/*proton tabs*/
vbox.tab-label-container.proton{display: grid; justify-items: safe center;}
/* vbox.tab-label-container.proton{display: grid; place-items: center;} */
vbox.tab-label-container.proton .tab-text.tab-label{overflow:hidden;}
/*proton disabled tabs*/
hbox.tab-label-container{display: grid; place-items: center;}
hbox.tab-label-container .tab-text.tab-label{overflow:hidden;}
```
i found that when i added this rule
```
.tab-label-container{display: -moz-box !important;}
```
above the others and proton is enabled i was getting what looked like duplicate text on the tabs, almost looking like your last screenshot but not quite.
![image](https://user-images.githubusercontent.com/6720184/121252412-7d231480-c897-11eb-948a-d895234b3c95.png)

**Comment by Yaron10** [comment]
> interesting, i was not aware of the safe keyword.

I'm not a pro and I wasn't even familiar with `grid`. :)
After reading your reply, I searched it and was lucky to come across `safe center`.
You deserve all the credit. Thank you.

> using the safe option it looks like the text only gets centered if it's shorter than the width of the container.

This makes sense. 👍 

> something that's driving me nuts is the tab text will jump when i mouse over it and i have no idea why it doesn't happen on my middle tab as seen in the video. It doesn't happen with proton disabled.

I'm not sure I understand.
I suppose it doesn't happen without any modifications. Can you pinpoint the culprit code? 

> i found that when i added this rule
.tab-label-container{display: -moz-box !important;}
...

This has happened to me too in the past few days while playing with Proton.

**Comment by Yaron10** [comment]
> the left tab i set labeldirection="rtl", middle and right tabs are both labeldirection="ltr".

Oops, I missed that part. Why should you do that? :)

**Comment by sean1138** [comment]
> > the left tab i set labeldirection="rtl", middle and right tabs are both labeldirection="ltr".
> 
> Oops, I missed that part. Why should you do that? :)

because you said your system is RTL, so i thought i should try to check that however i could in case it showed something different or weird.  the tab text jumping a little bit when i mouseover a tab with centered text shorter than the width of the tab happens for me regardless of rtl or ltr set on the element.

**Comment by sean1138** [comment]
fixed it so the text doesn't move for me when mouseover a tab with centered text shorter than tab width with proton enabled.  The issue was the tab close/X button image was getting wider when moused over to make it a bit easier to click (accessibility issue) so i figure just keep that close/X image the full width even when not moused over.
```
/*proton tabs center text if shorter than tab width*/
@media (-moz-proton){
  /* vbox.tab-label-container.proton{display: grid; justify-items: safe center;} */
  vbox.tab-label-container.proton{display: grid; place-items: safe center;}
  vbox.tab-label-container.proton .tab-text.tab-label{overflow:hidden;}
  /*keep the close X image the same/full width regardless of hover state so centered text doesn't jump when mouseover tab*/
  .tabbrowser-tab:not(:hover) > .tab-stack > .tab-content > .tab-close-button{
    padding-inline-start: 7px !important;
    width: 24px !important;
  }
}
/*proton disabled tabs center text if shorter than tab width*/
hbox.tab-label-container{display: grid; place-items: center;}
hbox.tab-label-container .tab-text.tab-label{overflow:hidden;}
```
demo:
https://files.catbox.moe/hqhz58.mp4

**Comment by Yaron10** [comment]
I was about to type the following lines when I was notified of your last post. :)

I should have realized the jumping text is not an off-topic issue but caused by `justify-items: safe center;`.

I used only those two lines and got the same jumping problem.
Adding one piece of my code at a time, I came to the same conclusion. You need to add:
```
.tab-close-button
{
	width: unset !important;
	padding-inline-start: 7px !important;
}
```

Interestingly, you actually get 8px. I'm new to Windows 10 and I've observed (in the past few days playing with Proton) a similar behavior in other FF elements as well. 

Well done! Thanks again.

**Comment by black7375** [comment]
Thank you to everyone who participated in the issue.
I'll add the following code to the wiki.

![image](https://user-images.githubusercontent.com/25581533/124236130-a127ed80-db05-11eb-9f8a-9233c34a0d21.png)

```css
vbox.tab-label-container {
  display: grid;
  justify-items: safe center;
}
vbox.tab-label-container .tab-text.tab-label{
  overflow:hidden;
}

.tab-close-button {
  width: unset !important;
  padding-inline-start: 7px !important;
}
```

---

@sean1138 You have been a great help in this issue and in #53, so I would like to add it to [`CREDITS`](https://github.com/black7375/Firefox-UI-Fix/blob/master/CREDITS) list.
Would you like to fill out information?
