### ISSUE TITLE
Remove the double "Manage bookmarks" in Firefox Bookmarks Menu

### ISSUE THREAD

**Issue by xlollomanx** [black7375/Firefox-UI-Fix#719]
### Is your feature request related to a problem?

Not really a problem but it's a small fix to avoid redudancy in bookmark manager. I'm posting here because I'm not sure if u want to implement this here. I found this code on firefox forums and I think it's a small change that could make things cleaner.

### The solution I'd like

Just add this code in this mod: 
```
/* hide "Manage Bookmarks" at the bottom */
#BMB_bookmarksShowAll { display:none!important;
}
```

This code will delete the the number 2 part in the screenshot below

### Screenshots or video

![immagine](https://github.com/black7375/Firefox-UI-Fix/assets/6764804/bdaceebd-66f6-4ce0-a52f-8c436de1450c)

### Alternatives I've considered

Maybe fork this project and do it myself but I think this can be beneficial to others.

**Comment by Patricek0056** [comment]
I think, that it is intentional decision. Why? Because if you e.g. have bookmarks menu too long, that you need scrolling; or if you have small display, then you have one in header, and one in end.

But I think, that it is useless in large displays (I have large display too).

I'm not against this bug, but I only wanted to say, that it is intentional in small displays/resolutions, or in long bookmarks list. 

And I think, that it shouldn't be permanently removed, but hiding this should be optional in `about:config`.

I hope, that your issue would be resolved soonest as possible.

**Comment by xlollomanx** [comment]
@Patricek0056 Fair enough, didn't tought about that. Honestly it's not like I can't live without this, but if it's a possible to make it configurable in some way I'll appreciate it much.

**Comment by black7375** [comment]
I think it's hard to show the all menu only when `overflowing="true"` because of the shadow dome structure.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/f40bc88c-0bda-4dcf-94fa-861e9875b82b)

It means that we should always hide one or show both of the menus.
The duplicate indication itself does not make a big inconvenience, but if I hide one of the menus, it is reasonable to maintain the current value because it can cause inconvenience for those using long bookmark menus.

---

If you are using a script, you can automatically overliding with `userChrome-overrides.css` file.

- https://github.com/black7375/Firefox-UI-Fix#installation-guide
- https://github.com/black7375/Firefox-UI-Fix/blob/master/docs/Project_Structure.md#overriding

**Comment by xlollomanx** [comment]
Thank u for the reply and the solution @black7375 .At this point I think we can close this, but I'll wait since I don't know if u want maintaing this open.

**Comment by Patricek0056** [comment]
If you want to discuss with others about this feature, then you can also put this on discussions, because discussions are better place to propose features.

**Comment by black7375** [comment]
I think we can close this issue for now.
