### ISSUE TITLE
Right click menu of Tree Style Tab no longer has separators - broken in FF116+

### ISSUE THREAD

**Issue by MagicalDrizzle** [black7375/Firefox-UI-Fix#758]
### Describe the bug

(FF116+)
1. Install Tree Style Tab.
2. Right click the vertical tab to bring up the menu.
3. Separators no longer appears.

### Expected behavior

(FF115-)
Separator appears.

### Screenshots

![116](https://github.com/black7375/Firefox-UI-Fix/assets/49761211/9c86f0f9-9043-4063-b9a9-1c5b95d8b99b)![115](https://github.com/black7375/Firefox-UI-Fix/assets/49761211/f0af4ffb-1c27-404d-9fa9-eb341c3b2fea)

 left is 116.0, right is 115.0.3

### OS

Windows 10

### Firefox Version

v116.0

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Unchanged from the user.js distributed with v8.0.0

**Comment by black7375** [comment]
The confirmation has changed the structure so that the sidebar content is isolated.
First of all, I worked briefly on separator, but in the long run, there are things I need to work on again so that the color of the sidebar context menu works with the theme.

**Comment by AuRiMaS666** [comment]
This is probably related to this, so I'll just add to this thread, instead of opening a new one.

There's no separators at all when right clicking items in the Library window. And, as mentioned by the OP, Sidebar separator colors are not right, they're too dark to match the background. When right clicking items directly on the Bookmarks Toolbar or using the dropdown menu, everything is displayed correctly.

This is on Win11, Firefox v117, it was the same on v116 as well.

![2023-08-29 11 22 26](https://github.com/black7375/Firefox-UI-Fix/assets/59185222/e3888dff-8ebc-4645-956e-530ad765be42) ![2023-08-29 11 19 58](https://github.com/black7375/Firefox-UI-Fix/assets/59185222/8f011be5-8d7f-4aee-94d0-2c5f63716433)

**Comment by black7375** [comment]
It was a smaller task than I thought.
Now it should work correctly.
Could you test it?

**Comment by AuRiMaS666** [comment]
Seems to work fine now, thanks!

![2023-09-03 13 05 51](https://github.com/black7375/Firefox-UI-Fix/assets/59185222/e2a95b0e-f142-49d7-8906-802bb4bfdce1) ![2023-09-03 13 06 59](https://github.com/black7375/Firefox-UI-Fix/assets/59185222/a1256745-4634-4c09-87da-e8b1588e7020)

**Comment by black7375** [comment]
@AuRiMaS666 
Thank you for fast feedback!!
