### ISSUE TITLE
I think new tab button must be changed.

### ISSUE THREAD

**Issue by SimYunSup** [black7375/Firefox-UI-Fix#95]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/47362439/122038634-c5e74a00-ce10-11eb-9a2b-2a6858597bcc.png)

Tab and new tab button heights do not match.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/47362439/122039071-3e4e0b00-ce11-11eb-8918-c5b382abe8ad.png)

I think new tab button should be changed like this.

**Comment by 7k5x** [comment]
I totally agree on that.

**Comment by ojaha065** [comment]
Yeah, I too agree. If the changes discussed in #27 are implemented, this could probably be changed at the same time.

**Comment by 7k5x** [comment]
Changing that won’t be much of a big deal, so let’s wait until someone opens a PR or the maintainer fixes it.

**Comment by black7375** [comment]
Have you tried using extension after placing them at the tabbar?
Then it looks not bad.
![image](https://user-images.githubusercontent.com/25581533/122139440-8896b280-ce38-11eb-96db-61522e110811.png)
![image](https://user-images.githubusercontent.com/25581533/122139474-9a785580-ce38-11eb-9ab1-a0211f7d6633.png)

This is probably because it treats it as a `button`.
The same goes for other browsers.
Photon(ver 88)
![image](https://user-images.githubusercontent.com/25581533/122139081-aa436a00-ce37-11eb-83a9-6d57ea1e7f70.png)

Edge
![image](https://user-images.githubusercontent.com/25581533/122139875-7bc68e80-ce39-11eb-9838-3091b44d2623.png)

Chromium
![image](https://user-images.githubusercontent.com/25581533/122140075-d6f88100-ce39-11eb-84d3-c9a37797259b.png)

---

But I think it's good to think of it as a metaphor for `potential tab`, and it's well worth a try.

This is the idea of ​​australis.
Basilisk
![image](https://user-images.githubusercontent.com/25581533/122141532-0fe62500-ce3d-11eb-8134-aff29c00f8f2.png)

Interesting.

**Comment by SimYunSup** [comment]
I didn't open this issue because of only the new tab button, but because I thought the tab and button didn't match.
![image](https://user-images.githubusercontent.com/47362439/122146290-bcea8d00-ce91-11eb-8ab3-bea7418c99a1.png)

I think my idea is poor, but I still think height of button on tabbar must be smaller than tab height. So I open this isssue.
So at least, button height change like below.
![image](https://user-images.githubusercontent.com/47362439/122147569-1f448d00-ce94-11eb-9edd-1802eb2c6e78.png)

I will try to change like australis style, but I think it will take a long time.

**Comment by black7375** [comment]
Then we need to modify all the buttons on the tab toolbar.

Another thing to consider.
In firefox, overscrolling occurs when a certain number of tabs are exceeded.
![image](https://user-images.githubusercontent.com/25581533/122149303-64909c80-ce4b-11eb-9117-e64c4f04a088.png)

At this point, the tab is the element behind it and should appear small.
![image](https://user-images.githubusercontent.com/25581533/122151206-aa9b2f80-ce4e-11eb-92a0-0c13d21bbd02.png)
![image](https://user-images.githubusercontent.com/25581533/122151231-b555c480-ce4e-11eb-856b-4ad0fbb93d7b.png)

**Comment by SimYunSup** [comment]
If you apply css below, all the button except scroll button is modified on windows.
```css
#TabsToolbar .toolbar-items .toolbarbutton-1 {
  margin: var(--tab-block-margin) 0 0 !important;
}
```
![image](https://user-images.githubusercontent.com/47362439/122155429-ed3a2780-cea1-11eb-8923-6dbd50d76bcd.png)

**Comment by black7375** [comment]
I tried it, but the height is increased by about 2px.
![image](https://user-images.githubusercontent.com/25581533/122159509-facdbe00-ce5d-11eb-91e3-37a82041ec36.png)
![image](https://user-images.githubusercontent.com/25581533/122159576-0de08e00-ce5e-11eb-8372-63a6ab138cb1.png)


In addition, it seems to be a complicated problem with vertical alignment problem and symmetry problem of upper and lower margins.
![122155429-ed3a2780-cea1-11eb-8923-6dbd50d76bcd](https://user-images.githubusercontent.com/25581533/122159000-1a181b80-ce5d-11eb-9faa-6b1204ae467e.png)

The larger the size, the easier it is to click(or touch), so there are UX advantages as well.
In that sense, it looks good that the size of the scroll button has been increased.
I'll apply it to the scroll button target right away.

However, other factors must be approached with caution due to trade-offs.
Let's go back to the beginning and fix it mainly for the new tab button, excluding other buttons.
